---
title: "First Knit"
author: "Dana Schroer"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### I attended Highschool at Quartz Hill High school and graduated the year 2023. I think both math and english are difficult for me but I perfer Math. I did the best in math and anatomy as well as biology.    
  

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### I have a PC that runs the windows program. I would say I'm roughly a 7 when it comes to computer stuff. I also have a high speed internet that works greatly at all times. The connection is very strong, but sometimes our internet cuts out cause someone ran into the box again.
  
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### Dana is my name but it's pronounced Donna. My name comes from Europe which is quite unique.        
  
   
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### I want to either become a doctor such as an optomitrest or a professer for Biology such as Bio 120 and possibly do marine research on Orcas. I would love to go to UCLA and hopefully the highest degree you can get which is a PH.D.        
  
   
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### I have been to multiple forigen countries such as Romania, Germany, Itlay, and etc. I would love to go to Iceland and Japan in the future. I also have never been in the military, but if I was drafted I hope I would be able to be in the Army Medical Department, because it will make me comfortable with medical emergencies.     
  
   
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### I'm taking this class because it's needed in order to transfer and might be important in the future. I would love to get an A in order to see a bright future at med school or any biology courses.    
   
 






  




